site_name: RTE Plugins Docs

repo_url: https://github.com/contentstack/rte-plugin-boilerplate
edit_uri: ""

nav:
  - Getting Started: 'index.md'
  - Prerequisites: 'prerequisites.md'
  - Create a Plugin: 'create_plugin.md'
  - RTE Methods: 'methods.md'
  - Editor Events: 'editor_events.md'
  - Dropdown Plugin: 'dropdown.md'


theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  features:
    - navigation.expand
    - content.code.annotate

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 